# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "test-atsuya-survey-app"
client_id = "8c95bd8925a148426bad46aee7b47fe3"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
dev_store_url = "test-atsuya-dev-store-20231005.myshopify.com"
